### PR TITLE
Rename to blueprint

### PR DESCRIPTION
**Pull request by plunkettscott**
This PR renames occurrences of spec to blueprint and renames the `spec` package to `blueprints` to hold all blueprints. The `game` spec has a new condition to check for the `type` of `game` in the root `blueprint` block like so:

```hcl
# Let Contaim know this is a Game blueprint for configuring a game server.
blueprint {
  type = "game"
}
```

While this change is unnecessary for the moment, as we add additional services like "database" to complement game servers it'll be necessary to ensure the user provides a blueprint of the correct type. This will also allow us to automatically determine the blueprint type when validating so that we do not have to rely on the user to specify the type, lowering the barrier to entry for new users.

Let me know what you think!

### CODE REVIEW

**Comment by plunkettscott** [comment]
I'll rename this repo once this merges to keep consistency between the package and repo for Go modules. We'll have to update our remotes locally when this changes, however i believe this is a better step forward.

**Comment by plunkettscott** [comment]
Validated the merge conflict resolution of this after merging in #3. All is well with that.

**Comment by spjy** [comment]
- `blueprint_hcl.go` - line 43
- `blueprint_json.go` - line 43
- `blueprint.go` - lines 17, 20, 25, 33, 34, 40, 41
- `parser.go` - not sure if you meant to keep these occurances?

**Comment by spjy** [comment]
Sorry a few more spots:
* `block_blueprint.go` - lines 15, 16
* `block_fetch.go` - lines 27, 28, 145
* `block_meta.go` - lines 17, 21, 63, 67
* `spec/schemas/root.go` - lines 8, 11, 13, 14, 19

**Pull request merged**
